import type {
  CalculationOutput,
  CalculationStep,
  ServoPulseParams,
  ServoPulseResult,
} from './types';

/**
 * Calculates RC servo control pulse width from angle, or angle from pulse duration (standard 50 Hz frame).
 */
export function calculateServoPulse(params: ServoPulseParams): CalculationOutput<ServoPulseResult> {
  const {
    pulseWidthUs,
    angleDegrees,
    minPulseUs = 544,
    maxPulseUs = 2400,
    frameRateHz = 50,
  } = params;

  if (minPulseUs >= maxPulseUs) {
    throw new Error('Minimum pulse width must be strictly less than maximum pulse width.');
  }
  if (frameRateHz <= 0) {
    throw new Error('Frame rate must be strictly greater than zero.');
  }

  const framePeriodMs = 1000 / frameRateHz; // 20 ms for 50 Hz
  const framePeriodUs = framePeriodMs * 1000; // 20,000 µs

  let finalAngle = angleDegrees;
  let finalPulseUs = pulseWidthUs;

  if (finalAngle === undefined && finalPulseUs === undefined) {
    throw new Error(
      'Provide either angle in degrees (0-180°) or pulse width in microseconds (µs).',
    );
  }

  const pulseSpan = maxPulseUs - minPulseUs;

  if (finalAngle !== undefined) {
    if (finalAngle < 0 || finalAngle > 180) {
      throw new Error('Servo angle must be between 0° and 180°.');
    }
    finalPulseUs = minPulseUs + (finalAngle / 180) * pulseSpan;
  } else if (finalPulseUs !== undefined) {
    if (finalPulseUs < minPulseUs || finalPulseUs > maxPulseUs) {
      throw new Error(`Pulse width must be between ${minPulseUs} µs and ${maxPulseUs} µs.`);
    }
    finalAngle = ((finalPulseUs - minPulseUs) / pulseSpan) * 180;
  }

  const steps: CalculationStep[] = [];
  const formula =
    'Angle = [(Pulse - MinPulse) / (MaxPulse - MinPulse)] × 180°, Pulse = MinPulse + (Angle / 180°) × Span';

  const pulseMs = (finalPulseUs ?? 0) / 1000;
  const dutyPercent = ((finalPulseUs ?? 0) / framePeriodUs) * 100;

  steps.push({
    label: 'Standard 50 Hz Servo Refresh Frame',
    math: `T_frame = 1 / ${frameRateHz} Hz = ${framePeriodMs.toFixed(1)} ms (${framePeriodUs.toLocaleString()} µs)`,
    explanation: 'RC servos expect control pulses refreshed every 20 ms (50 Hz).',
  });

  steps.push({
    label: 'Angle ↔ Pulse Translation',
    math: `${(finalAngle ?? 0).toFixed(1)}° ↔ ${(finalPulseUs ?? 0).toFixed(1)} µs (${pulseMs.toFixed(3)} ms)`,
    explanation: `Maps linearly between min (${minPulseUs} µs) at 0° and max (${maxPulseUs} µs) at 180° (neutral 90° = ${((minPulseUs + maxPulseUs) / 2).toFixed(0)} µs).`,
  });

  steps.push({
    label: 'PWM Duty Cycle on 20 ms Frame',
    math: `Duty = (${(finalPulseUs ?? 0).toFixed(1)} µs / ${framePeriodUs.toLocaleString()} µs) × 100% = ${dutyPercent.toFixed(2)}%`,
    explanation: 'Actual duty cycle generated by the microcontroller timer for servo positioning.',
  });

  return {
    result: {
      angleDegrees: Number((finalAngle ?? 0).toFixed(1)),
      pulseWidthUs: Number((finalPulseUs ?? 0).toFixed(1)),
      pulseWidthMs: Number(pulseMs.toFixed(3)),
      framePeriodMs: Number(framePeriodMs.toFixed(1)),
      dutyCyclePercent: Number(dutyPercent.toFixed(2)),
    },
    formula,
    steps,
    unit: '° / µs',
  };
}
